# Numpy

In [ ]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
arr = np.random.randint(21, size=(4,7))
arr

array([[17,  0,  5, 15, 19, 12, 10],
       [ 3, 14,  9,  3,  7,  7,  9],
       [ 0,  7,  8,  5,  0, 10,  7],
       [16,  1, 19, 17, 12,  5,  0]])

In [ ]:
(arr-np.min(arr))/(np.max(arr)-np.min(arr))

array([[0.85, 0.35, 1.  , 0.35, 0.9 , 0.  , 0.3 ],
       [0.95, 0.25, 0.65, 0.4 , 0.25, 0.6 , 0.35],
       [0.5 , 0.4 , 0.8 , 0.7 , 0.95, 0.3 , 0.7 ],
       [0.4 , 0.35, 0.4 , 0.95, 0.8 , 0.15, 0.45]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a1 = np.random.randint(11, size=(8,10))
a1[a1.sum(axis=1).argmin()],a1.sum(axis=1).argmin()

(array([3, 1, 2, 1, 2, 4, 6, 1, 3, 0]), 7)

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
a1 = np.random.randint(10, size=(1,10))
a2 = np.random.randint(10, size=(1,10))
r = np.linalg.norm(a1-a2)
r

12.083045973594572

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1,2,4],[-3,1,2],[-3,0,1]])
B = np.array([[3,-1],[2,1]])
C = np.array([[7,21],[11,8],[8,4]])
A1 = np.linalg.inv(A)
B1 = np.linalg.inv(B)
C1 = C*(-1)
x = A1 @ C1 @ B1
x

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Продолжение

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
recipe = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)
print(recipe[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('Среднее значение ', np.mean(recipe[:,1:], 0))
print('Максимальные значения ',np.max(recipe[:,1:],0))
print('Минимальные значения ',np.min(recipe[:,1:],0))
print('Медианы ',np.median(recipe[:,1:],0))

Среднее значение  [2.16010017e+04 9.05528000e+00]
Максимальные значения  [2147483647         39]
Минимальные значения  [0 1]
Медианы  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
maxim = np.quantile(recipe[:,1], 0.75, axis = 0)
print(maxim)
print(recipe[recipe[:,1]<=maxim])

65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
a = np.count_nonzero(recipe[:,1] == 0)
recipe[recipe[:,1]==0] = 1
print( np.count_nonzero(recipe[:,1] == 0))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
a = np.unique(recipe[:,0])
print(len(a))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
a, num = np.unique(recipe[:,2], return_counts=True)
print(np.column_stack((a, num)))

[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
arr = recipe[recipe[:,2]<=5]
a = np.copy(arr)
print(a)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
a = recipe[:,2]/recipe[:,1]
print( max(a))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
a = recipe[:,1].argsort()
b = recipe[a][-100:]
print(np.mean(b[:,2], axis = 0))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
a = np.random.randint(recipe.shape[0], size = 10)
print(recipe[a])

[[394093      8      5]
 [276023    135      5]
 [133994  30255      8]
 [396699     50     10]
 [324877     50      9]
 [159619     60      8]
 [ 23374     75      9]
 [105069     40     10]
 [448225     20      8]
 [193947     65      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
a = np.mean(recipe[:,2], axis = 0)
print(recipe[recipe[:,2]<a])
print('----')
print((100*len(recipe[recipe[:,2]<a]))/len(recipe))

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]
----
58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
a = np.append(recipe, np.zeros((recipe.shape[0],1), dtype = 'int32'), axis = 1)
a[np.logical_and(a[:,1]<=20,a[:,2]<=5)] = 1
a = a.copy()
print(a)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [     1      1      1      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
b = a[a[:,3] == 1]
print((100*len(b)/len(recipe)))

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
a1 = recipe[recipe[:,1]<10]
a2 = recipe[np.logical_and(recipe[:,1]>=10, recipe[:,1]<20)]
a3 = recipe[recipe[:,1]>=20]
maxim = min(len(a1), len(a2), len(a3))
b = np.array([[a1[:maxim-1],a2[:maxim-1],a3[:maxim-1]]])
print(b)

[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [     1      1      1]
   [420725      5      3]
   [     1      1      1]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [107094     10      4]
   [  9831     15      7]
   [335859     12     14]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [ 92137     80      9]
   [168901     25      7]
   [392339     35     13]]]]
